version: 2

# Use target.database when available (set in profile). Override via env or profile.
sources:
  - name: staging
    database: "{{ target.database }}"
    schema: staging
    description: Raw data loaded from S3 into Snowflake staging.
    tables:
      - name: listings
        description: Staging table for listing records.
        # Add when your staging load populates a loaded_at column:
        # freshness: { warn_after: { count: 12, period: hour }, error_after: { count: 24, period: hour } }
        # loaded_at_field: loaded_at
      - name: bookings
        description: Staging table for booking records.
      - name: hosts
        description: Staging table for host records.