aws_dbt_snowflake_project:
  outputs:
    dev:
      account: WDOGKVX-UTC81757
      database: AIRBNB
      password: Sublime@06010601
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: PAVANKOLLI0601
      warehouse: COMPUTE_WH
  target: dev
