# Silver layer: cleaned and business-ready; incremental with unique_key.

version: 2

models:
  - name: silver_bookings
    description: Cleaned bookings with derived TOTAL_AMOUNT; one row per BOOKING_ID.
    columns:
      - name: BOOKING_ID
        description: Primary key.
        tests: [unique, not_null]
      - name: LISTING_ID
        description: FK to silver_listings.
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('silver_listings')
                field: LISTING_ID
      - name: CREATED_AT
        tests: [not_null]

  - name: silver_hosts
    description: Cleaned hosts with RESPONSE_RATE_QUALITY; one row per HOST_ID.
    columns:
      - name: HOST_ID
        description: Primary key.
        tests: [unique, not_null]
      - name: CREATED_AT
        tests: [not_null]

  - name: silver_listings
    description: Cleaned listings with PRICE_PER_NIGHT_TAG; one row per LISTING_ID.
    columns:
      - name: LISTING_ID
        description: Primary key.
        tests: [unique, not_null]
      - name: HOST_ID
        description: FK to silver_hosts.
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('silver_hosts')
                field: HOST_ID
      - name: CREATED_AT
        tests: [not_null]
