# Gold layer: analytics-ready OBT and ephemeral subsets for snapshots.
# Model contract on OBT enforces column set and types so downstream/BI breaks are caught at build.

version: 2

models:
  - name: obt
    description: One Big Table — one row per booking with denormalized listing and host attributes.
    config:
      contract:
        enforced: true
    columns:
      - name: BOOKING_ID
        description: Booking primary key.
        data_type: string
        tests: [unique, not_null]
      - name: LISTING_ID
        description: FK to listing.
        data_type: string
        tests: [not_null]
      - name: BOOKING_DATE
        data_type: date
      - name: TOTAL_AMOUNT
        data_type: number
      - name: SERVICE_FEE
        data_type: number
      - name: CLEANING_FEE
        data_type: number
      - name: BOOKING_STATUS
        data_type: string
      - name: CREATED_AT
        description: Booking created timestamp.
        data_type: timestamp_ntz
        tests: [not_null]
      - name: HOST_ID
        description: FK to host (from listing).
        data_type: string
        tests: [not_null]
      - name: PROPERTY_TYPE
        data_type: string
      - name: ROOM_TYPE
        data_type: string
      - name: CITY
        data_type: string
      - name: COUNTRY
        data_type: string
      - name: ACCOMMODATES
        data_type: number
      - name: BEDROOMS
        data_type: number
      - name: BATHROOMS
        data_type: number
      - name: PRICE_PER_NIGHT
        data_type: number
      - name: PRICE_PER_NIGHT_TAG
        data_type: string
      - name: LISTING_CREATED_AT
        data_type: timestamp_ntz
      - name: HOST_NAME
        data_type: string
      - name: HOST_SINCE
        data_type: date
      - name: IS_SUPERHOST
        data_type: boolean
      - name: RESPONSE_RATE
        data_type: number
      - name: RESPONSE_RATE_QUALITY
        data_type: string
      - name: HOST_CREATED_AT
        data_type: timestamp_ntz

  - name: bookings
    description: Ephemeral subset of OBT used as source for dim_bookings snapshot.
  - name: hosts
    description: Ephemeral subset of OBT used as source for dim_hosts snapshot.
  - name: listings
    description: Ephemeral subset of OBT used as source for dim_listings snapshot.
  - name: fact
    description: Ephemeral mart joining OBT to current snapshot dims on LISTING_ID and HOST_ID.
